name: Uikit
version: '${project.version}'
main: org.slavawins.uikit.Uikit
api-version: '1.20'
depend:
  - reassets
commands:
  mycom:
    description: Базовая
    usage: <command>
  xquester:
    description: Базовая
    usage: <command>
  xquester next:
    description: Следующий диалог с нпц
    usage: <command> [npcId]
  xquester questeventmake:
    description: Выполнить квест
    usage: <command> [player] [eventType] [eventId] [amount]
  xquestereditor:
    description: Общий раздел комманд